import crypto from 'node:crypto';
import {googleJson,response,fail} from './_google.js';
import {readSession, requestOriginAllowed} from './_session.js';
const sheet='users';
const hash=p=>{const s=crypto.randomBytes(16).toString('hex');return `${s}:${crypto.pbkdf2Sync(p,s,120000,32,'sha256').toString('hex')}`};
async function rows(){const id=process.env.GOOGLE_SHEET_ID,r=encodeURIComponent(`${sheet}!A:ZZ`),x=await googleJson(`https://sheets.googleapis.com/v4/spreadsheets/${id}/values/${r}`),v=x.values||[];return v.length?v.slice(1).map(a=>Object.fromEntries(v[0].map((h,i)=>[h,a[i]??'']))):[]}
async function put(rs){const id=process.env.GOOGLE_SHEET_ID,r=encodeURIComponent(`${sheet}!A:ZZ`),h=['id','username','displayName','role','passwordHash','active','createdAt','updatedAt'],v=[h,...rs.map(x=>h.map(k=>x[k]??''))];await googleJson(`https://sheets.googleapis.com/v4/spreadsheets/${id}/values/${r}:clear`,{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});await googleJson(`https://sheets.googleapis.com/v4/spreadsheets/${id}/values/${r}?valueInputOption=USER_ENTERED`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({majorDimension:'ROWS',values:v})})}
const auth=e=>readSession(e.headers?.cookie||e.headers?.Cookie);
export async function handler(e){const u=auth(e);if(!u)return fail(401,'UNAUTHENTICATED','Sign in required.');if(u.role!=='admin')return fail(403,'FORBIDDEN','Admin access required.');if(e.httpMethod!=='GET'&&!requestOriginAllowed(e))return fail(403,'FORBIDDEN','Cross-origin request blocked.');try{const rs=await rows();if(e.httpMethod==='GET')return response(200,{success:true,data:rs.map(x=>({id:x.id,username:x.username,displayName:x.displayName,role:x.role,active:String(x.active).toLowerCase()!=='false',createdAt:x.createdAt,updatedAt:x.updatedAt}))});if(e.httpMethod!=='POST'&&e.httpMethod!=='PATCH')return fail(405,'METHOD_NOT_ALLOWED','GET, POST or PATCH required.');const b=JSON.parse(e.body||'{}');if(e.httpMethod==='POST'){if(!b.username||!b.password)return fail(400,'VALIDATION_ERROR','Username and password are required.');if(String(b.username).length>80||!/^[A-Za-z0-9._-]+$/.test(String(b.username)))return fail(400,'VALIDATION_ERROR','Username contains invalid characters.');if(String(b.password).length<8)return fail(400,'VALIDATION_ERROR','Password must be at least 8 characters.');if(rs.some(x=>x.username.toLowerCase()===String(b.username).toLowerCase()))return fail(409,'DUPLICATE','Username already exists.');const now=new Date().toISOString();rs.push({id:`USR-${String(rs.length+1).padStart(5,'0')}`,username:String(b.username).trim(),displayName:String(b.displayName||b.username).trim(),role:b.role==='admin'?'admin':'staff',passwordHash:hash(String(b.password)),active:'true',createdAt:now,updatedAt:now});await put(rs);return response(200,{success:true})}const x=rs.find(v=>v.id===b.id);if(!x)return fail(404,'NOT_FOUND','User not found.');if(b.displayName!==undefined)x.displayName=String(b.displayName).trim();if(b.role!==undefined)x.role=b.role==='admin'?'admin':'staff';if(b.active!==undefined)x.active=b.active?'true':'false';if(b.password)x.passwordHash=hash(String(b.password));x.updatedAt=new Date().toISOString();if(x.username===u.username&&x.active==='false')return fail(400,'VALIDATION_ERROR','You cannot deactivate your own account.');await put(rs);return response(200,{success:true})}catch(err){return fail(500,'USERS_ERROR','Unable to manage users.')}}
